obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h265_bitstream.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h265_core.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h265_entropy.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h265_nal.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h265_vdma.o
