
CFLAGS_KERNEL	+= -I$(srctree)/arch/mips/xburst/soc-PRJ007/chip-PRJ007/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-y		+= common/
obj-$(CONFIG_BOARD_GOAT)		+= $(CONFIG_BOARD_NAME)/
obj-$(CONFIG_BOARD_VELA)		+= $(CONFIG_BOARD_NAME)/
