obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h264_core.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h264_vdma.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h264_cabac.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h264_nal.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += h264_header.o
